include:
  - applications/compose.yaml
  - environments/compose.yaml
  - infrastructure/compose.yaml

x-restart: &restart
  restart: unless-stopped

services:
  traefik:
    <<: *restart
    depends_on:
      frontend: { condition: service_healthy }
    ports: [8000:80, 4443:4443, 4443:4443/udp]
  signoz:
    <<: *restart
    ports: [8080:8080]
  mail_server:
    <<: *restart
    ports: [8025:8025]
  frontend:
    <<: *restart
    depends_on:
      python-interface: { condition: service_healthy }
      master-collector: { condition: service_healthy }
  python-interface:
    <<: *restart
    depends_on:
      master-collector: { condition: service_healthy }
  kratos:
    <<: *restart
  oathkeeper:
    <<: *restart
  host-collector:
    <<: *restart
  integrations-collector:
    <<: *restart
  master-collector:
    <<: *restart
  clickhouse:
    <<: *restart
  postgres:
    <<: *restart
