x-frontend-dep: &frontend-dep
  frontend: { condition: service_healthy }

x-otel-collector-dep: &otel-collector-dep
  otel-collector: { condition: service_healthy }

x-clickhouse-dep: &clickhouse-dep
  clickhouse: { condition: service_healthy }

x-frontend-env: &frontend-env
  FRONTEND_HOST: frontend
  FRONTEND_PORT: 3000

x-otel-collector-env: &otel-collector-env
  OTEL_COLLECTOR_HOST: otel-collector
  OTEL_COLLECTOR_GRPC: 4317
  OTEL_COLLECTOR_HTTP: 4318

x-clickhouse-env: &clickhouse-env
  CLICKHOUSE_USER: myuser
  CLICKHOUSE_PASS: mypass
  CLICKHOUSE_HOST: clickhouse
  CLICKHOUSE_PORT: 9000
  CLICKHOUSE_PATH: mydatabase

services:
  traefik:
    depends_on: { <<: [*frontend-dep, *otel-collector-dep] }
    environment: { <<: [*frontend-env, *otel-collector-env] }

  frontend:
    depends_on: { <<: [*otel-collector-dep] }
    environment: { <<: [*frontend-env, *otel-collector-env] }

  otel-collector-migrator:
    depends_on: { <<: [*clickhouse-dep] }
    environment: { <<: [*clickhouse-env] }

  otel-collector:
    depends_on: { <<: [*clickhouse-dep] }
    environment: { <<: [*clickhouse-env, *otel-collector-env] }

  signoz:
    depends_on:
      otel-collector-migrator: { condition: service_completed_successfully }
    environment:
      SIGNOZ_TOKENIZER_JWT_SECRET: mysecret
      <<: [*clickhouse-env]

  clickhouse:
    environment: { <<: [*clickhouse-env] }
