x-restart: &restart
  restart: unless-stopped

x-frontend-dep: &frontend-dep
  frontend: { condition: service_healthy }

x-otel-services-dep: &otel-services-dep
  otel-services: { condition: service_healthy }

x-clickhouse-dep: &clickhouse-dep
  clickhouse: { condition: service_healthy }

services:
  traefik:
    <<: *restart
    depends_on: { <<: [*frontend-dep, *otel-services-dep] }
    env_file: [./.env/.frontend, ./.env/.otel-collector]

  frontend:
    <<: *restart
    depends_on: { <<: [*otel-services-dep] }
    env_file: [./.env/.frontend, ./.env/.otel-collector]

  otel-migrator:
    depends_on: { <<: [*clickhouse-dep] }
    env_file: [./.env/.clickhouse]

  otel-host:
    <<: *restart
    env_file: [./.env/.otel-collector]

  otel-integrations:
    <<: *restart
    depends_on: { <<: [*clickhouse-dep] }
    env_file: [./.env/.clickhouse, ./.env/.otel-collector]

  otel-services:
    <<: *restart
    depends_on: { <<: [*clickhouse-dep] }
    env_file: [./.env/.clickhouse, ./.env/.otel-collector]

  signoz:
    <<: *restart
    depends_on:
      otel-migrator: { condition: service_completed_successfully }
    env_file: [./.env/.clickhouse, ./.env/.signoz]

  signoz-bootstrap:
    env_file: [./.env/.clickhouse, ./.env/.signoz]

  clickhouse:
    <<: *restart
    env_file: [./.env/.clickhouse, ./.env/.otel-collector]
