#!/bin/sh
set -eux

export SERVE_API_PORT=$OATHKEEPER_PORT
export AUTHENTICATORS_COOKIE_SESSION_CONFIG_CHECK_SESSION_URL=http://$KRATOS_HOST:$KRATOS_PUBLIC_PORT/sessions/whoami
export AUTHENTICATORS_BEARER_TOKEN_CONFIG_CHECK_SESSION_URL=http://$KRATOS_HOST:$KRATOS_PUBLIC_PORT/sessions/whoami
export AUTHENTICATORS_COOKIE_SESSION_CONFIG_ONLY_0=$KRATOS_COOKIE_NAME
export TRACING_PROVIDERS_OTLP_SERVER_URL=$OTEL_COLLECTOR_HOST:$OTEL_COLLECTOR_HTTP
export TRACING_SERVICE_NAME=${OTEL_SERVICE_NAME:-oathkeeper}
export SERVE_PROMETHEUS_PORT=$OATHKEEPER_PROMETHEUS_PORT

exec "$@"
