x-otel-collector-image: &otel-collector-image
  build: .

services:
  otel-collector-migrator:
    <<: *otel-collector-image
    command:
      - /bin/sh
      - -c
      - |
        set -eux
        /signoz-otel-collector migrate bootstrap
        /signoz-otel-collector migrate sync up
        /signoz-otel-collector migrate async up

  otel-collector:
    <<: *otel-collector-image
    depends_on:
      otel-collector-migrator: { condition: service_completed_successfully }
    volumes: [./config.yaml:/etc/otel/config.yaml:ro]
