#!/bin/sh
set -eux

export DSN=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$KRATOS_DB?sslmode=disable

kratos migrate sql -e --yes

export SELFSERVICE_DEFAULT_BROWSER_RETURN_URL=https://$DOMAIN:$PORT/
export SELFSERVICE_FLOWS_LOGIN_UI_URL=https://$DOMAIN:$PORT/login
export SELFSERVICE_FLOWS_REGISTRATION_UI_URL=https://$DOMAIN:$PORT/registration
export SELFSERVICE_FLOWS_RECOVERY_UI_URL=https://$DOMAIN:$PORT/recovery
export SELFSERVICE_FLOWS_VERIFICATION_UI_URL=https://$DOMAIN:$PORT/verification
export SELFSERVICE_FLOWS_SETTINGS_UI_URL=https://$DOMAIN:$PORT/settings
export SELFSERVICE_FLOWS_ERROR_UI_URL=https://$DOMAIN:$PORT/error
export SERVE_PUBLIC_BASE_URL=https://$DOMAIN:$PORT/auth
export SERVE_ADMIN_PORT=$KRATOS_ADMIN_PORT
export SESSION_COOKIE_NAME=$KRATOS_COOKIE_NAME
export SECRETS_COOKIE=$KRATOS_SECRET_COOKIE
export SECRETS_CIPHER=$KRATOS_SECRET_CIPHER
export COURIER_SMTP_CONNECTION_URI=smtp://$SMTP_HOST:$SMTP_PORT/?disable_starttls=true
export TRACING_PROVIDERS_OTLP_SERVER_URL=$MASTER_COLLECTOR_HOST:$MASTER_COLLECTOR_HTTP
export TRACING_SERVICE_NAME=${OTEL_SERVICE_NAME:-kratos}

exec "$@"
