api:
  dashboard: false

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":${PORT}"
    http3:
      advertisedPort: ${PORT}

experimental:
  otlpLogs: true

metrics:
  otlp:
    grpc:
      endpoint: "${OTEL_COLLECTOR_HOST}:${OTEL_COLLECTOR_GRPC}"
      insecure: true
    addRoutersLabels: true
    pushInterval: 1s

log:
  level: INFO
  otlp:
    grpc:
      endpoint: "${OTEL_COLLECTOR_HOST}:${OTEL_COLLECTOR_GRPC}"
      insecure: true

accessLog:
  otlp:
    grpc:
      endpoint: "${OTEL_COLLECTOR_HOST}:${OTEL_COLLECTOR_GRPC}"
      insecure: true

tracing:
  otlp:
    grpc:
      endpoint: "${OTEL_COLLECTOR_HOST}:${OTEL_COLLECTOR_GRPC}"
      insecure: true
