#!/bin/sh
set -eux

export DSN=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$KRATOS_DB?sslmode=disable

kratos migrate sql -e --yes

export SELFSERVICE_DEFAULT_BROWSER_RETURN_URL=https://$DOMAIN:$PORT/
export SELFSERVICE_FLOWS_LOGIN_UI_URL=https://$DOMAIN:$PORT/login
export SELFSERVICE_FLOWS_REGISTRATION_UI_URL=https://$DOMAIN:$PORT/registration
export SELFSERVICE_FLOWS_RECOVERY_UI_URL=https://$DOMAIN:$PORT/recovery
export SELFSERVICE_FLOWS_VERIFICATION_UI_URL=https://$DOMAIN:$PORT/verification
export SELFSERVICE_FLOWS_SETTINGS_UI_URL=https://$DOMAIN:$PORT/settings
export SERVE_PUBLIC_BASE_URL=https://$DOMAIN:$PORT/auth
export SERVE_ADMIN_PORT=$KRATOS_ADMIN_PORT
export SECRETS_COOKIE=q1w2e3r4t5y6u7i8o9p0aqswdefrgthy
export SECRETS_CIPHER=q1w2e3r4t5y6u7i8o9p0aqswdefrgthy
export COURIER_SMTP_CONNECTION_URI=smtp://$SMTP_HOST:$SMTP_PORT/?disable_starttls=true
export TRACING_PROVIDERS_OTLP_SERVER_URL=$OTEL_COLLECTOR_HOST:$OTEL_COLLECTOR_HTTP

exec "$@"
