http:
  routers:
    frontend:
      entryPoints:
        - websecure
      rule: "PathPrefix(`/`)"
      priority: 1
      service: frontend-service
      tls: {}
  services:
    frontend-service:
      loadBalancer:
        servers:
          - url: 'http://{{ env "FRONTEND_HOST" }}:{{ env "FRONTEND_PORT" }}'
