connectors:
  signozmeter:
    metrics_flush_interval: 1h

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:${env:OTEL_COLLECTOR_GRPC}
      http:
        endpoint: 0.0.0.0:${env:OTEL_COLLECTOR_HTTP}

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
    path: /health

processors:
  resourcedetection:
    detectors: [env, system]

  memory_limiter:
    check_interval: 1s
    spike_limit_mib: 512
    limit_mib: 1024

  batch/logs:
    timeout: 1s
    send_batch_size: 512
    send_batch_max_size: 1024

  batch/traces:
    timeout: 2s
    send_batch_size: 512
    send_batch_max_size: 1024

  batch/metrics:
    timeout: 5s
    send_batch_size: 512
    send_batch_max_size: 1024

  transform:
    log_statements:
      - context: log
        statements:
          - merge_maps(attributes, ParseJSON(body), "upsert") where IsMatch(body, "^\\{")
          - set(attributes["log.type"], "plaintext") where not IsMatch(body, "^\\{")

  signozspanmetrics:
    metrics_exporter: signozclickhousemetrics
    metrics_flush_interval: 60s
    latency_histogram_buckets:
      - 100us
      - 1ms
      - 2ms
      - 6ms
      - 10ms
      - 50ms
      - 100ms
      - 250ms
      - 500ms
      - 1000ms
      - 1400ms
      - 2000ms
      - 5s
      - 10s
      - 20s
      - 40s
      - 60s
    aggregation_temporality: AGGREGATION_TEMPORALITY_DELTA
    enable_exp_histogram: true

exporters:
  signozclickhousemetrics:
    dsn: ${env:SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_DSN}/signoz_metrics
    timeout: 5s
    sending_queue:
      enabled: true
      num_consumers: 8
      queue_size: 5000

  clickhouselogsexporter:
    dsn: ${env:SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_DSN}/signoz_logs
    use_new_schema: true
    timeout: 5s
    sending_queue:
      enabled: true
      num_consumers: 8
      queue_size: 5000

  clickhousetraces:
    datasource: ${env:SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_DSN}/signoz_traces
    low_cardinal_exception_grouping: false
    use_new_schema: true
    timeout: 5s
    sending_queue:
      enabled: true
      num_consumers: 8
      queue_size: 5000

  signozclickhousemeter:
    dsn: ${env:SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_DSN}/signoz_meter
    timeout: 5s
    sending_queue:
      enabled: true
      num_consumers: 8
      queue_size: 5000

  metadataexporter:
    enabled: true
    dsn: ${env:SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_DSN}/signoz_metadata
    timeout: 5s
    cache:
      provider: in_memory

  debug:
    verbosity: detailed

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, memory_limiter, batch/traces, signozspanmetrics]
      exporters: [clickhousetraces, metadataexporter, signozmeter]

    metrics:
      receivers: [otlp]
      processors: [resourcedetection, memory_limiter, batch/metrics]
      exporters: [signozclickhousemetrics, metadataexporter, signozmeter]

    logs:
      receivers: [otlp]
      processors: [transform, resourcedetection, memory_limiter, batch/logs]
      exporters: [clickhouselogsexporter, metadataexporter, signozmeter]

    metrics/meter:
      receivers: [signozmeter]
      processors: [resourcedetection, memory_limiter, batch/metrics]
      exporters: [signozclickhousemeter]
